#!/usr/bin/env python3
"""Write the v7r2c pilot config (continuation of v7r2 seed 2903, scripted arm only).

v7r2c continues the best v7r2 policy so far (seed 2903 scripted at one million
decisions: 46/96 holdout wins vs the public scripts, warm start 19/96) under the
unchanged v7r2 recipe (gae_lambda 0.95, no anchor, entropy factorized-v2,
scripted-only initial opponents, 64 envs / 8 workers / 4 threads, target_kl
0.02, lr 1e-4) with:

* critic_warmup_updates 0 (allowed only for a declared continuation: the
  initializer already carries a trained critic);
* phase_order ["nominal", "nominal-league"] (level 11 throughout; the
  continuation counts from 0 to 1M, then the league runs to 5M);
* continuation_* fields binding the v7r2 seed-2903 scripted 1M checkpoint by
  absolute path, file digest, its own pilot config digest and decision count
  (weights only; optimizer, counters, simulator and RNG start fresh);
* runtime pins -> pilot-runtime-v4, output dir pilot/v7r2c-launch/runs/s2903.

The config must declare three seeds and both arms (CouncilPilotConfig); only
seed 2903 scripted is ever launched by this kit (launch.sh refuses the rest,
and the trainer refuses a zero warm-up for any other scripted run).
Only the fields in CHANGES (plus the header comment) differ from the base.
Written with open("x") and made read-only.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path("/Users/sam/Desktop/code/clasher")
RC = ROOT / "reports/strategy_council_20260928"
RUNTIME = RC / "m0/runtime-snapshots/pilot-runtime-v4"
OUT = RC / "pilot/v7r2c-launch"
V7R2 = RC / "pilot/v7r2-launch"
BASE = ROOT / "configs/council-pilot-local.toml"
SEEDS = (2903,)
CONTINUATION_CHECKPOINT = V7R2 / "runs/s2903/seed-2903/scripted/policy_decisions_001000000.pt"
CONTINUATION_CHECKPOINT_SHA = "c7aae667e45073bfab442b9d36a4b2c45bca7321df442d8ebfac419e191dc522"
CONTINUATION_SOURCE_CONFIG = V7R2 / "configs/council-pilot-v7r2-seed2903.toml"
CONTINUATION_SOURCE_CONFIG_SHA = "472041eded91815c304b09eab08f9f0fb803ce1e1dd09bdeff053c1d47a79236"
HEADER = (
    "# Council pilot v7r2c: continuation of v7r2 seed {seed} scripted from its 1M checkpoint. Runs from\n"
    "# pilot-runtime-v4. v7r2 recipe (gae 0.95, no anchor, entropy factorized-v2, scripted-only initial\n"
    "# opponents, CPU layout 64/8/4) with critic warm-up 0 and phases nominal then nominal-league (level 11).\n"
    "# Only seed {seed} scripted is launched (pilot/v7r2c-launch/launch.sh refuses every other run).\n"
    "# Generated by pilot/v7r2c-launch/make_configs.py from configs/council-pilot-local.toml; do not edit.\n"
    "# Requires the ledger-issued m0-tier-a-fresh-v7 admission receipt (source_root native-final-v7).\n"
)
INSERT_AFTER = "device"


def changes(seed: int) -> dict[str, object]:
    return {
        "source_root": str(RUNTIME),
        "gamedata_path": str(RUNTIME / "gamedata.json"),
        "source_pins_path": str(RUNTIME / "pilot-source-pins.json"),
        "nominal_admission_path": str(RC / "m0/readiness/tier-a-fresh-v7/admission.json"),
        "output_dir": str(OUT / f"runs/s{seed}"),
        "num_envs": 64,
        "actor_workers": 8,
        "torch_threads": 4,
        "smoke_decisions": 98304,
        "rollout_inference": "worker",
        "inference_device": "cpu",
        "entropy_coef": 0.0,
        "action_type_entropy_coef": 0.0,
        "location_entropy_coef": 0.0,
        "conditional_slot_entropy_coef": 0.003,
        "initial_opponent_policies": ["scripted"],
        "critic_warmup_updates": 0,
        "phase_order": ["nominal", "nominal-league"],
        "continuation_seed": seed,
        "continuation_checkpoint_path": str(CONTINUATION_CHECKPOINT),
        "continuation_checkpoint_sha256": CONTINUATION_CHECKPOINT_SHA,
        "continuation_source_config_sha256": CONTINUATION_SOURCE_CONFIG_SHA,
        "continuation_source_decisions": 1_000_000,
    }


def render(seed: int) -> str:
    text = BASE.read_text()
    lines = text.splitlines(keepends=True)
    assert lines[0].startswith("#"), "base header comment moved"
    body = lines[1:]
    inserted: list[str] = []
    for key, value in changes(seed).items():
        literal = json.dumps(value) if isinstance(value, (str, list)) else str(value)
        pattern = re.compile(rf"^{re.escape(key)} = .*$")
        hits = [i for i, line in enumerate(body) if pattern.match(line.rstrip("\n"))]
        assert len(hits) <= 1, (key, hits)
        if hits:
            body[hits[0]] = f"{key} = {literal}\n"
        else:
            inserted.append(f"{key} = {literal}\n")
    anchor = [i for i, line in enumerate(body) if line.startswith(f"{INSERT_AFTER} = ")]
    assert len(anchor) == 1, anchor
    body[anchor[0] + 1 : anchor[0] + 1] = inserted
    return HEADER.format(seed=seed) + "".join(body)


def main() -> None:
    import hashlib

    digest = lambda p: hashlib.sha256(p.read_bytes()).hexdigest()  # noqa: E731
    assert digest(CONTINUATION_CHECKPOINT) == CONTINUATION_CHECKPOINT_SHA, "continuation checkpoint changed"
    assert digest(CONTINUATION_SOURCE_CONFIG) == CONTINUATION_SOURCE_CONFIG_SHA, "v7r2 config changed"
    (OUT / "configs").mkdir(parents=True, exist_ok=True)
    for seed in SEEDS:
        path = OUT / "configs" / f"council-pilot-v7r2c-seed{seed}.toml"
        with path.open("x") as stream:
            stream.write(render(seed))
        path.chmod(0o444)
        print(path)


if __name__ == "__main__":
    main()
