#!/usr/bin/env python3
"""Write the three per-seed v7r3 pilot configs from configs/council-pilot-local.toml.

v7r3 = the v7r2 recipe (entropy factorized-v2, initial_opponent_policies
["scripted"], 64 envs / 8 actor workers / 4 torch threads, worker inference,
target_kl 0.02, lr 1e-4) plus the user-approved v7r3 changes
(pilot/v7r3-proposal/PROPOSAL.md; the anchor was approved at 0.01, not 0.05):

* gae_lambda 0.95 -> 0.99 (credit window ~20 -> ~100 decisions);
* critic_warmup_updates 20 -> 60 (scripted arm; scratch stays 0 by code);
* anchor_policy_kl_coef 0 -> 0.01 (scripted arm only, anchored by code to
  output_dir/seed-N/initialization/scripted.pt, the rebound warm start);
* phase_order ["nominal", "nominal-league"]: level 11 throughout; after the
  one-million nominal phase the league runs to 5M with retained milestones
  2M/3M/4M/5M; only the nominal Tier A receipt is needed;
* runtime pins -> pilot-runtime-v3, new output dirs (pilot/v7r3-launch/runs/sN).

Only the fields in CHANGES (plus the header comment) differ from the base;
every other line is copied byte-for-byte. Keys absent from the base are inserted
right after ``device``. Files are written with open("x") and made read-only.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path("/Users/sam/Desktop/code/clasher")
RC = ROOT / "reports/strategy_council_20260928"
RUNTIME = RC / "m0/runtime-snapshots/pilot-runtime-v3"
OUT = RC / "pilot/v7r3-launch"
BASE = ROOT / "configs/council-pilot-local.toml"
SEEDS = (2901, 2902, 2903)
HEADER = (
    "# Council pilot v7r3, seed {seed} (both arms). Runs from pilot-runtime-v3 (native-final-v7 plus\n"
    "# training-only modules, admission-scope decision v1). v7r2 recipe (entropy factorized-v2,\n"
    "# scripted-only initial opponents, CPU layout 64/8/4) plus v7r3: gae_lambda 0.99, critic warm-up 60,\n"
    "# warm-start policy-KL anchor 0.01 (scripted arm), phases nominal then nominal-league (level 11).\n"
    "# Generated by pilot/v7r3-launch/make_configs.py from configs/council-pilot-local.toml; do not edit.\n"
    "# Requires the ledger-issued m0-tier-a-fresh-v7 admission receipt (source_root native-final-v7).\n"
)
INSERT_AFTER = "device"


def changes(seed: int) -> dict[str, object]:
    return {
        "source_root": str(RUNTIME),
        "gamedata_path": str(RUNTIME / "gamedata.json"),
        "source_pins_path": str(RUNTIME / "pilot-source-pins.json"),
        "nominal_admission_path": str(RC / "m0/readiness/tier-a-fresh-v7/admission.json"),
        "output_dir": str(OUT / f"runs/s{seed}"),
        "num_envs": 64,
        "actor_workers": 8,
        "torch_threads": 4,
        "smoke_decisions": 98304,
        "rollout_inference": "worker",
        "inference_device": "cpu",
        "entropy_coef": 0.0,
        "action_type_entropy_coef": 0.0,
        "location_entropy_coef": 0.0,
        "conditional_slot_entropy_coef": 0.003,
        "initial_opponent_policies": ["scripted"],
        "gae_lambda": 0.99,
        "critic_warmup_updates": 60,
        "anchor_policy_kl_coef": 0.01,
        "phase_order": ["nominal", "nominal-league"],
    }


def render(seed: int) -> str:
    text = BASE.read_text()
    lines = text.splitlines(keepends=True)
    assert lines[0].startswith("#"), "base header comment moved"
    body = lines[1:]
    inserted: list[str] = []
    for key, value in changes(seed).items():
        literal = json.dumps(value) if isinstance(value, (str, list)) else str(value)
        pattern = re.compile(rf"^{re.escape(key)} = .*$")
        hits = [i for i, line in enumerate(body) if pattern.match(line.rstrip("\n"))]
        assert len(hits) <= 1, (key, hits)
        if hits:
            body[hits[0]] = f"{key} = {literal}\n"
        else:
            inserted.append(f"{key} = {literal}\n")
    anchor = [i for i, line in enumerate(body) if line.startswith(f"{INSERT_AFTER} = ")]
    assert len(anchor) == 1, anchor
    body[anchor[0] + 1 : anchor[0] + 1] = inserted
    return HEADER.format(seed=seed) + "".join(body)


def main() -> None:
    (OUT / "configs").mkdir(parents=True, exist_ok=True)
    for seed in SEEDS:
        path = OUT / "configs" / f"council-pilot-v7r3-seed{seed}.toml"
        with path.open("x") as stream:
            stream.write(render(seed))
        path.chmod(0o444)
        print(path)


if __name__ == "__main__":
    main()
