#!/usr/bin/env python3
"""Write the three per-seed v7r2 pilot configs from configs/council-pilot-local.toml.

v7r2 = the v7r1 kit with the user-approved recipe fix (pilot/diagnosis-1M,
2026-10-01) on pilot runtime pilot-runtime-v2 (native-final-v7 plus 4 changed
training-only modules and 2 changed orchestration scripts):

* entropy factorization: entropy_coef 0, action_type_entropy_coef 0,
  location_entropy_coef 0, conditional_slot_entropy_coef 0.003 (recipe
  "factorized-v2"; the joint-entropy term no longer applies at all);
* initial_opponent_policies = ["scripted"]: the untrained random control is
  not published in the scripted arm's opponent pool (first million and league);
  the scratch arm keeps it (its own initializer must be a published opponent);
* new output dirs (pilot/v7r2-launch/runs/sN) so the v7r1 runs stay as evidence.

Throughput settings are unchanged from v7r1 (64 envs, 8 actor workers, 4 torch
threads, worker inference, smoke_decisions 98,304). Only the fields in CHANGES
(plus the header comment) differ from the base; every other line is copied
byte-for-byte. Keys absent from the base are inserted right after ``device``.
Files are written with open("x") and made read-only (the budget ledger,
rebind receipts and resume checks bind the config SHA-256).
"""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path("/Users/sam/Desktop/code/clasher")
RC = ROOT / "reports/strategy_council_20260928"
RUNTIME = RC / "m0/runtime-snapshots/pilot-runtime-v2"
OUT = RC / "pilot/v7r2-launch"
BASE = ROOT / "configs/council-pilot-local.toml"
SEEDS = (2901, 2902, 2903)
HEADER = (
    "# Council pilot v7r2, seed {seed} (both arms). Runs from pilot-runtime-v2 (native-final-v7 plus\n"
    "# 4 training-only modules, admission-scope decision v1). Recipe fix (pilot/diagnosis-1M): entropy\n"
    "# factorized-v2, random control out of the scripted arm's opponent pool. CPU layout 64/8/4.\n"
    "# Generated by pilot/v7r2-launch/make_configs.py from configs/council-pilot-local.toml; do not edit.\n"
    "# Requires the ledger-issued m0-tier-a-fresh-v7 admission receipt (source_root native-final-v7).\n"
)
INSERT_AFTER = "device"


def changes(seed: int) -> dict[str, object]:
    return {
        "source_root": str(RUNTIME),
        "gamedata_path": str(RUNTIME / "gamedata.json"),
        "source_pins_path": str(RUNTIME / "pilot-source-pins.json"),
        "nominal_admission_path": str(RC / "m0/readiness/tier-a-fresh-v7/admission.json"),
        "output_dir": str(OUT / f"runs/s{seed}"),
        "num_envs": 64,
        "actor_workers": 8,
        "torch_threads": 4,
        "smoke_decisions": 98304,
        "rollout_inference": "worker",
        "inference_device": "cpu",
        "entropy_coef": 0.0,
        "action_type_entropy_coef": 0.0,
        "location_entropy_coef": 0.0,
        "conditional_slot_entropy_coef": 0.003,
        "initial_opponent_policies": ["scripted"],
    }


def render(seed: int) -> str:
    text = BASE.read_text()
    lines = text.splitlines(keepends=True)
    assert lines[0].startswith("#"), "base header comment moved"
    body = lines[1:]
    inserted: list[str] = []
    for key, value in changes(seed).items():
        literal = json.dumps(value) if isinstance(value, (str, list)) else str(value)
        pattern = re.compile(rf"^{re.escape(key)} = .*$")
        hits = [i for i, line in enumerate(body) if pattern.match(line.rstrip("\n"))]
        assert len(hits) <= 1, (key, hits)
        if hits:
            body[hits[0]] = f"{key} = {literal}\n"
        else:
            inserted.append(f"{key} = {literal}\n")
    anchor = [i for i, line in enumerate(body) if line.startswith(f"{INSERT_AFTER} = ")]
    assert len(anchor) == 1, anchor
    body[anchor[0] + 1 : anchor[0] + 1] = inserted
    return HEADER.format(seed=seed) + "".join(body)


def main() -> None:
    (OUT / "configs").mkdir(parents=True, exist_ok=True)
    for seed in SEEDS:
        path = OUT / "configs" / f"council-pilot-v7r2-seed{seed}.toml"
        with path.open("x") as stream:
            stream.write(render(seed))
        path.chmod(0o444)
        print(path)


if __name__ == "__main__":
    main()
