"""Self-contained research summary; every value comes from checked results."""
import json
from pathlib import Path
root=Path(__file__).resolve().parent;r=json.loads((root/'results.json').read_text())
html='''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><style>
body{font-family:var(--font-sans,system-ui);color:var(--foreground,#222);margin:0;font-size:14px}p{line-height:1.5;margin:8px 0}small{color:var(--muted-foreground,#666)}button{padding:7px 10px;margin:0 7px 7px 0;border:1px solid var(--border,#bbb);border-radius:var(--radius,6px);background:transparent;color:inherit;cursor:pointer}button[aria-pressed=true]{background:var(--accent-surface,#eef);color:var(--accent-surface-foreground,#224)}svg{width:100%;height:260px;display:block}table{border-collapse:collapse;width:100%;font-variant-numeric:tabular-nums;margin-top:12px}td,th{padding:9px 4px;border-bottom:1px solid var(--border,#ddd);text-align:right}td:first-child,th:first-child{text-align:left}th{font-size:12px;color:var(--muted-foreground,#666)}.key{font-weight:650}.note{font-size:12px;margin-top:12px}@media(max-width:480px){body{font-size:12px}td,th{padding:7px 2px}svg{height:225px}}
</style></head><body><p class="key">1,000 paired seeds per arm · d=27 · exploration only</p><p id="finding"></p><div id="tabs"></div><svg id="plot" role="img" aria-label="Paired change in loss rate with 95 percent exploratory bootstrap intervals" viewBox="0 0 700 260"></svg><small id="caption"></small><table><thead><tr><th>Arm</th><th>Wins / losses</th><th>Under-4 arrivals</th><th>CPU p50 / p95</th><th>Raw wall &gt;200 ms</th></tr></thead><tbody id="rows"></tbody></table><p class="note">Pointwise paired bootstrap intervals; 2,000 shared seed resamples. Synthetic fixed-work search. No registered eval/heldout access. Zero empirical rates are not population upper bounds. Timing is from loaded idle-scheduled hosts; this screen does not approve live deployment.</p><script>const R=__DATA__;
const choices=[['Loss change','game_loss_fraction',100,'percentage points; fewer losses is left'],['Under-4 change','arrival_under4_fraction',100,'percentage points'],['Defender affordability','no_affordable_defender_in_hand_fraction',100,'percentage points; fewer unaffordable-defender arrivals is left'],['CPU latency cost','mean_cpu_decision_ms',1,'milliseconds']];
const names={'0':'Baseline',E:'E',H12:'H12',H16:'H16',W:'W',EW:'E + W',EH:'E + H',HW:'H + W',EHW:'E + H + W'};
const pct=x=>x==null?'—':(x*100).toFixed(1)+'%';
const loss=R.paired_contrasts[ R.arms[R.arms.length-1] ].game_loss_fraction;
document.querySelector('#finding').textContent='Selected combination: '+names[R.arms[R.arms.length-1]]+'. Its paired loss change is '+(loss.difference*100).toFixed(1)+' pp ['+(loss.ci95[0]*100).toFixed(1)+', '+(loss.ci95[1]*100).toFixed(1)+']. The 200 ms wall budget is '+(R.required_latency_budget_met?'met.':'not met.');
document.querySelector('#rows').innerHTML=R.arms.map(a=>{const o=R.outcomes[a],l=R.latency[a];return '<tr><td>'+names[a]+'</td><td>'+o.wins+' / '+o.losses+'</td><td>'+pct(R.estimates[a].arrival_under4_fraction.value)+'</td><td>'+l.process_cpu.p50_ms.toFixed(0)+' / '+l.process_cpu.p95_ms.toFixed(0)+' ms</td><td>'+pct(l.raw_wall.over200_fraction)+'</td></tr>'}).join('');
let current=0;function draw(j){current=j;const mobile=window.matchMedia('(max-width:480px)').matches;document.querySelector('#plot').setAttribute('viewBox',mobile?'0 0 360 260':'0 0 700 260');document.querySelectorAll('button').forEach((b,i)=>b.setAttribute('aria-pressed',i===j));const [title,key,scale,unit]=choices[j],data=R.arms.slice(1).map(a=>({a,...R.paired_contrasts[a][key]})).filter(d=>d.ci95);let lo=Math.min(0,...data.map(d=>d.ci95[0]*scale)),hi=Math.max(0,...data.map(d=>d.ci95[1]*scale));const pad=Math.max((hi-lo)*.14,.2);lo-=pad;hi+=pad;const x=v=>(mobile?75:110)+(v-lo)/(hi-lo)*(mobile?156:430);let svg='<line x1="'+x(0)+'" y1="10" x2="'+x(0)+'" y2="220" stroke="var(--muted-foreground,#aaa)" stroke-dasharray="3 4"/>';data.forEach((d,i)=>{const y=28+i*38,v=d.difference*scale,a=d.ci95[0]*scale,b=d.ci95[1]*scale;svg+='<text x="3" y="'+(y+4)+'" fill="var(--foreground,#222)" font-size="'+(mobile?12:14)+'">'+names[d.a]+'</text><line x1="'+x(a)+'" y1="'+y+'" x2="'+x(b)+'" y2="'+y+'" stroke="var(--chart-1,#4678cf)" stroke-width="3"/><circle cx="'+x(v)+'" cy="'+y+'" r="5" fill="var(--chart-1,#4678cf)"/><text x="'+(mobile?242:552)+'" y="'+(y+4)+'" fill="var(--foreground,#222)" font-size="'+(mobile?10:13)+'">'+(v>=0?'+':'')+v.toFixed(1)+' ['+a.toFixed(1)+', '+b.toFixed(1)+']</text>'});for(let i=0;i<5;i++){const v=lo+(hi-lo)*i/4;svg+='<text x="'+x(v)+'" y="247" text-anchor="middle" fill="var(--muted-foreground,#777)" font-size="12">'+v.toFixed(1)+'</text>'}document.querySelector('#plot').innerHTML=svg;document.querySelector('#caption').textContent=title+' vs baseline, 95% paired CI · '+unit;}
choices.forEach(([name],i)=>{const b=document.createElement('button');b.textContent=name;b.type='button';b.onclick=()=>draw(i);document.querySelector('#tabs').appendChild(b)});draw(0);window.addEventListener('resize',()=>draw(current));console.log('Rendered '+R.arms.length+' arms; paired N='+R.paired_seeds);</script></body></html>'''
html=html.replace('__DATA__',json.dumps(r,separators=(',',':')).replace('</','<\\/'));(root/'comparison.html').write_text(html)
