# Source on a leased host. No shared environment or home-directory changes.
export CLASHER_LEASE_ROOT=/mpac/sdicks02/repos/clasher-lease
export CLASHER_ROOT=$CLASHER_LEASE_ROOT/repo
export UV_CACHE_DIR=$CLASHER_LEASE_ROOT/cache/uv
export UV_PYTHON_INSTALL_DIR=$CLASHER_LEASE_ROOT/tools/uv-python
export UV_PYTHON_BIN_DIR=$CLASHER_LEASE_ROOT/tools/python-bin
export UV_TOOL_DIR=$CLASHER_LEASE_ROOT/tools/uv-tools
export UV_TOOL_BIN_DIR=$CLASHER_LEASE_ROOT/tools/uv-tools-bin
export UV_PROJECT_ENVIRONMENT=$CLASHER_ROOT/.venv
export UV_PYTHON=3.12.13 UV_PYTHON_PREFERENCE=only-managed UV_LINK_MODE=copy
export UV_CONCURRENT_DOWNLOADS=2 UV_CONCURRENT_BUILDS=1 UV_CONCURRENT_INSTALLS=2
export CARGO_HOME=$CLASHER_LEASE_ROOT/tools/cargo
export RUSTUP_HOME=$CLASHER_LEASE_ROOT/tools/rustup
export RUSTUP_TOOLCHAIN=1.97.1-x86_64-unknown-linux-gnu
export CARGO_TARGET_DIR=$CLASHER_LEASE_ROOT/build/engine-rs CARGO_BUILD_JOBS=1 CARGO_INCREMENTAL=0
export XDG_CACHE_HOME=$CLASHER_LEASE_ROOT/cache XDG_CONFIG_HOME=$CLASHER_LEASE_ROOT/config XDG_DATA_HOME=$CLASHER_LEASE_ROOT/share
export TMPDIR=$CLASHER_LEASE_ROOT/tmp
export CUDA_CACHE_PATH=$CLASHER_LEASE_ROOT/cache/cuda TRITON_CACHE_DIR=$CLASHER_LEASE_ROOT/cache/triton
export TORCHINDUCTOR_CACHE_DIR=$CLASHER_LEASE_ROOT/cache/torchinductor TORCH_HOME=$CLASHER_LEASE_ROOT/cache/torch
export HF_HOME=$CLASHER_LEASE_ROOT/cache/hf MPLCONFIGDIR=$CLASHER_LEASE_ROOT/cache/matplotlib
export YOLO_CONFIG_DIR=$CLASHER_LEASE_ROOT/config/yolo
export PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1
export OMP_NUM_THREADS=1 MKL_NUM_THREADS=1 OPENBLAS_NUM_THREADS=1 NUMBA_NUM_THREADS=1
export RAYON_NUM_THREADS=1 TORCHINDUCTOR_COMPILE_THREADS=1 MAX_JOBS=1
export PYTHONPATH=$CLASHER_ROOT/src:$CLASHER_ROOT/engine-rs:$CLASHER_ROOT/scripts
export CLASHER_PROJECTILE_CATALOG=$CLASHER_LEASE_ROOT/data/decoded-logic-1e505767/projectiles.csv
export PATH=$CLASHER_LEASE_ROOT/tools/uv:$CARGO_HOME/bin:/usr/local/bin:/usr/bin:/bin
export UV_INSTALL_DIR=$CLASHER_LEASE_ROOT/tools/uv
export PIP_CACHE_DIR=$CLASHER_LEASE_ROOT/cache/pip NUMBA_CACHE_DIR=$CLASHER_LEASE_ROOT/cache/numba
export XDG_STATE_HOME=$CLASHER_LEASE_ROOT/state
