#!/usr/bin/env python3
"""Write the three per-seed v6 pilot configs from configs/council-pilot-local.toml.

Each file runs both arms (scripted, scratch) of one seed. Only the fields in
CHANGES (plus the header comment) differ from the base; every other line is
copied byte-for-byte. Files are written with open("x") and should be made
read-only before the first --execute (the budget ledger and resume check the
config SHA-256).
"""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path("/Users/sam/Desktop/code/clasher")
RC = ROOT / "reports/strategy_council_20260928"
SNAP = RC / "m0/runtime-snapshots/native-final-v6"
OUT = RC / "pilot/v6-launch"
BASE = ROOT / "configs/council-pilot-local.toml"
SEEDS = (2901, 2902, 2903)
HEADER = (
    "# Council pilot v6, seed {seed} (both arms). Runs from the admitted snapshot native-final-v6.\n"
    "# Generated by pilot/v6-launch/make_configs.py from configs/council-pilot-local.toml; do not edit.\n"
    "# Requires the ledger-issued m0-tier-a-fresh-v6 admission receipt.\n"
)


def changes(seed: int) -> dict[str, object]:
    return {
        "source_root": str(SNAP),
        "gamedata_path": str(SNAP / "gamedata.json"),
        "source_pins_path": str(OUT / "source-pins-native-final-v6.json"),
        "nominal_admission_path": str(RC / "m0/readiness/tier-a-fresh-v6/admission.json"),
        "output_dir": str(OUT / f"runs/s{seed}"),
        "num_envs": 8,
    }


def render(seed: int) -> str:
    text = BASE.read_text()
    lines = text.splitlines(keepends=True)
    assert lines[0].startswith("#"), "base header comment moved"
    body = lines[1:]
    for key, value in changes(seed).items():
        literal = json.dumps(value) if isinstance(value, str) else str(value)
        pattern = re.compile(rf"^{re.escape(key)} = .*$")
        hits = [i for i, line in enumerate(body) if pattern.match(line.rstrip("\n"))]
        assert len(hits) == 1, (key, hits)
        body[hits[0]] = f"{key} = {literal}\n"
    return HEADER.format(seed=seed) + "".join(body)


def main() -> None:
    (OUT / "configs").mkdir(parents=True, exist_ok=True)
    for seed in SEEDS:
        path = OUT / "configs" / f"council-pilot-v6-seed{seed}.toml"
        with path.open("x") as stream:
            stream.write(render(seed))
        print(path)


if __name__ == "__main__":
    main()
