#!/usr/bin/env python3
"""Write the three per-seed v7r4h pilot configs from configs/council-pilot-local.toml.

v7r4h = "PPO from the human model" (user-approved 2026-10-02; replaces the held
3-seed v7r3 run). The v7r2 recipe (entropy factorized-v2, 64 envs / 8 actor
workers / 4 torch threads, worker inference, lr 1e-4, clip 0.2, 2 epochs,
target_kl 0.02, gamma 1.0, gae_lambda 0.95, reward potential 0.05, level 11)
with:

* initializer = the human-imitation checkpoint
  human-prior-p16/checkpoints/human-bc-natural-seed2903.pt (declared by path,
  file digest and reconstruction-manifest digest; weights only), in the
  scripted-arm slot of every seed. It is a research artifact under the
  2026-10-01 amendment, NOT a Tier A admitted arm (recorded in every launch
  record and checkpoint);
* critic_warmup_updates 60 (actor frozen; the human checkpoint's critic is
  untrained);
* anchor_policy_kl_coef 0.05, anchored by code to the same human checkpoint;
* initial_opponent_policies ["scripted"]: the pool is the seed's scripted warm
  start (rebound from v7r1, as v7r2/v7r3 did) plus the human checkpoint; no
  random control;
* phase_order ["nominal", "nominal-league"]: level 11 throughout; 1M nominal +
  diagnostic evaluation, then the league to 5M with retained milestones
  2M/3M/4M/5M, each diagnostically evaluated by the runner;
* runtime pins -> pilot-runtime-v5, output dirs pilot/v7r4h-launch/runs/sN.

The config schema requires both arms; this kit never launches the scratch arm
(launch.sh refuses it). Only the fields in CHANGES (plus the header comment)
differ from the base; every other line is copied byte-for-byte. Keys absent
from the base are inserted right after ``device``. Files are written with
open("x") and made read-only.
"""

from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path

ROOT = Path("/Users/sam/Desktop/code/clasher")
RC = ROOT / "reports/strategy_council_20260928"
RUNTIME = RC / "m0/runtime-snapshots/pilot-runtime-v5"
OUT = RC / "pilot/v7r4h-launch"
BASE = ROOT / "configs/council-pilot-local.toml"
SEEDS = (2901, 2902, 2903)
HUMAN_CHECKPOINT = RC / "human-prior-p16/checkpoints/human-bc-natural-seed2903.pt"
HUMAN_CHECKPOINT_SHA = "49be14806a7e7e6ab26621e25230d3f6f7f0be4d84aabd480cbb8097de4ab482"
HUMAN_RECON_MANIFEST_SHA = "5158a4ac7d003795b9557d61c590d0dc386587d4dfb391b8f75dd327711f950b"
HEADER = (
    "# Council pilot v7r4h, seed {seed}: PPO from the human-imitation checkpoint (human-prior-p16,\n"
    "# human-bc-natural-seed2903.pt; research artifact, NOT a Tier A admitted arm) in the scripted-arm slot.\n"
    "# Runs from pilot-runtime-v5. v7r2 recipe (gae 0.95, entropy factorized-v2, 64/8/4, target_kl 0.02,\n"
    "# lr 1e-4) plus critic warm-up 60, policy-KL anchor 0.05 to the human checkpoint, pool = warm start +\n"
    "# human checkpoint (no random control), phases nominal then nominal-league (level 11).\n"
    "# The scratch arm is declared only because the schema requires it; it is never launched.\n"
    "# Generated by pilot/v7r4h-launch/make_configs.py from configs/council-pilot-local.toml; do not edit.\n"
    "# Requires the ledger-issued m0-tier-a-fresh-v7 admission receipt (source_root native-final-v7).\n"
)
INSERT_AFTER = "device"


def changes(seed: int) -> dict[str, object]:
    return {
        "source_root": str(RUNTIME),
        "gamedata_path": str(RUNTIME / "gamedata.json"),
        "source_pins_path": str(RUNTIME / "pilot-source-pins.json"),
        "nominal_admission_path": str(RC / "m0/readiness/tier-a-fresh-v7/admission.json"),
        "output_dir": str(OUT / f"runs/s{seed}"),
        "num_envs": 64,
        "actor_workers": 8,
        "torch_threads": 4,
        "smoke_decisions": 98304,
        "rollout_inference": "worker",
        "inference_device": "cpu",
        "entropy_coef": 0.0,
        "action_type_entropy_coef": 0.0,
        "location_entropy_coef": 0.0,
        "conditional_slot_entropy_coef": 0.003,
        "initial_opponent_policies": ["scripted"],
        "critic_warmup_updates": 60,
        "anchor_policy_kl_coef": 0.05,
        "phase_order": ["nominal", "nominal-league"],
        "human_prior_checkpoint_path": str(HUMAN_CHECKPOINT),
        "human_prior_checkpoint_sha256": HUMAN_CHECKPOINT_SHA,
        "human_prior_recon_manifest_sha256": HUMAN_RECON_MANIFEST_SHA,
    }


def render(seed: int) -> str:
    text = BASE.read_text()
    lines = text.splitlines(keepends=True)
    assert lines[0].startswith("#"), "base header comment moved"
    body = lines[1:]
    inserted: list[str] = []
    for key, value in changes(seed).items():
        literal = json.dumps(value) if isinstance(value, (str, list)) else str(value)
        pattern = re.compile(rf"^{re.escape(key)} = .*$")
        hits = [i for i, line in enumerate(body) if pattern.match(line.rstrip("\n"))]
        assert len(hits) <= 1, (key, hits)
        if hits:
            body[hits[0]] = f"{key} = {literal}\n"
        else:
            inserted.append(f"{key} = {literal}\n")
    anchor = [i for i, line in enumerate(body) if line.startswith(f"{INSERT_AFTER} = ")]
    assert len(anchor) == 1, anchor
    body[anchor[0] + 1 : anchor[0] + 1] = inserted
    return HEADER.format(seed=seed) + "".join(body)


def main() -> None:
    digest = hashlib.sha256(HUMAN_CHECKPOINT.read_bytes()).hexdigest()
    assert digest == HUMAN_CHECKPOINT_SHA, "human-prior checkpoint changed"
    (OUT / "configs").mkdir(parents=True, exist_ok=True)
    for seed in SEEDS:
        path = OUT / "configs" / f"council-pilot-v7r4h-seed{seed}.toml"
        with path.open("x") as stream:
            stream.write(render(seed))
        path.chmod(0o444)
        print(path)


if __name__ == "__main__":
    main()
