"""Render aggregate only after the complete reporting reduction."""
import argparse,json
from pathlib import Path

def pct(x):return f'{100*x:.2f}'
def ci(row):
    if row['value'] is None or row['ci95'] is None:return 'undefined'
    return f"{pct(row['value'])} [{pct(row['ci95'][0])}, {pct(row['ci95'][1])}]"
def main():
    ap=argparse.ArgumentParser();ap.add_argument('--results',type=Path,required=True);ap.add_argument('--out',type=Path,required=True);a=ap.parse_args();r=json.loads(a.results.read_text())
    assert r['terminal_games']==3000 and r['paired_seeds']==600 and not r['smoke']
    q=json.loads((a.out.parent/'receipts/qualification.json').read_text())
    lines=['# K anytime W search', '',f"Completed {r['reduced_at_utc']}. Frozen exploration; **3,000 terminal games, 600 fresh paired seeds per arm**, v1 policy opponent, symmetric d=27/capacity1, five decks/25 matchups, alternating seats. Draws remain separate; loss means opponent wins. No heldout, live or Mac access.", '', '| Arm | W/L/D | Loss %, 95% CI | Loss change vs K0, pp, 95% CI | Retention %, 95% CI | v1 fallback %, 95% CI | Wall p50/p95/p99, ms |','|---|---:|---:|---:|---:|---:|---:|']
    for arm in ('K0','K1','K4','K4h','KU'):
        out=r['outcomes'][arm];lat=r['latency'][arm]['wall']
        lines.append(f"| {arm} | {out['wins']}/{out['losses']}/{out['draws']} | {ci(out['loss'])} | {ci(r['loss_change_vs_K0'][arm])} | {ci(r['retention'][arm])} | {ci(r['fallback'][arm])} | {lat['p50_ms']:.1f}/{lat['p95_ms']:.1f}/{lat['p99_ms']:.1f} |")
    advance=', '.join(r['advance_arms']) or 'none'
    lines+=['',f"**Decision rules:** advance **{advance}** (upper95% CI of arm−K0 loss change≤−10pp). **Kill anytime W: {'YES' if r['kill_anytime_W'] else 'NO'}**, because K4’s loss-change CI {'includes' if r['kill_anytime_W'] else 'excludes'}0. Rules are exactly the frozen plan; neither statistical significance alone nor retention substitutes for the−10pp threshold.", '', 'Retention=(K0 loss−arm loss)/(K0 loss−KU loss); its CI uses the same paired seed resamples. KU is the unlimited screen8 ceiling. K0 is one-core deadline baseline. K1 completes WAIT/WAIT10 (one rollout set), then timed waits, then scans every play and refines top8. K4 uses the identical scorer with four GIL-release threads/private clones; each game pins five physical cores. K4h ranks with an80-tick coarse scan, then recomputes all three styles at160 for retained plays. K1/K4 reuse the160-tick balanced score in refinement. Final reduction retains original candidate order and the frozen1e-9 tie threshold.', '', '**Complete-score admission:** every eligible candidate has all three160-tick style scores finished before the192ms scoring cutoff. Partial/late roots never count. The200ms timer starts before public observation, v1 fallback sampling, belief, candidates and reconstruction;8ms is reserved for reduction/submission. KU has no deadline. The table includes full own decision calls, including first calls; opponent and intermediate five-tick maintenance are excluded. Native cancellation checks each tick; observed wall overruns expose OS/return residuals.', '', '| Arm | Cutoff %, 95% CI | Wall >200ms % | Own decisions | Game CPU hours |', '|---|---:|---:|---:|---:|']
    for arm in ('K0','K1','K4','K4h','KU'):
        lat=r['latency'][arm]['wall'];lines.append(f"| {arm} | {ci(r['cutoff'][arm])} | {pct(lat['over200_fraction'])} | {lat['decisions']} | {r['game_cpu_seconds'][arm]/3600:.2f} |")
    lines+=['',f"Qualification before games: K1/K4 exact frozen screen8 actions and retained scores125/125 each; one/four-thread vectors identical125/125; native zero-budget roots immutable125/125;12 injected-clock tests passed. K4h agreement **{q['counts']['K4h_agreement']}/125 ({100*q['counts']['K4h_agreement']/125:.1f}%)** is descriptive, not a gate. Source and v1 adapter pins match E1; only generic GIL-release build feature was enabled. No v3 or combat transition.", '',f"Seeds:4503601407370496+[0,600); excluded smoke4503601417370496+[0,8),40 terminal games. Freeze **0f2a9ec8**; implementation **8237f993**. [Plan](plan.json), [seed audit](seed-audit.json), [qualification](receipts/qualification.json), [runtime03](receipts/runtime-pin-03.json), [runtime01](receipts/runtime-pin-01.json), [counts/CIs/audits](results.json), [progress](PROGRESS-K.md), [X interface](INTERFACE.md).", '', 'Bootstrap:5,000 shared resamples of paired seed, pointwise95% percentile intervals, unadjusted. Pairing covers shuffled decks and seat; every seed runs all five arms on the same host. Each matchup/seat has12 seeds.600 reporting games per arm are retained. Fallback/cutoff CIs resample per-game numerator/denominator totals; KU’s zero fallback denominator is its own decision calls.', '',f"Fleet:03 physical CPUs0–59 and01 physical CPUs0–39, no SMT siblings, nice10/SCHED_IDLE, BLAS/Torch/Rayon1, CUDA disabled, caches under/mpac.03 perception cache services stayed up; X4 parent/loader CPUs and siblings were excluded. Minimum observed MemAvailable **{r['min_memavailable_GiB']:.2f}GiB**. Jobs use owned setsid-f detach wrapper with closed stdin and durable PID/PGID records. Raw games/logs remain under/mpac on03/01. No04/08/leased hosts/05 sims.", '', 'These are exploration results under fleet load, not Mac or live deadline qualification.']
    if r['advance_arms']:
        lines+=['', 'The advancing-arm Mac E4 v2 note is [prepared here](MAC-E4-V2.md). Mac execution remains outside this worker’s scope.']
    a.out.write_text('\n'.join(lines)+'\n')
if __name__=='__main__':main()
