#!/usr/bin/env python3
"""Write the three per-seed v7r1 pilot configs from configs/council-pilot-local.toml.

v7r1 = the v7 kit moved onto the pilot runtime pilot-runtime-v1 (native-final-v7
plus 3 changed training-only modules, admission-scope decision v1) with the
throughput settings from pilot/throughput/README.md (all three seeds on CPU,
64 envs, 8 actor workers, 4 torch threads, worker-side inference, a
98,304-decision smoke because 100,000 is not divisible by 64).

Each file runs both arms (scripted, scratch) of one seed. Only the fields in
CHANGES (plus the header comment) differ from the base; every other line is
copied byte-for-byte. Keys absent from the base are inserted right after
``device``. Files are written with open("x") and must be made read-only before
the first --execute (the budget ledger and resume check the config SHA-256).
"""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path("/Users/sam/Desktop/code/clasher")
RC = ROOT / "reports/strategy_council_20260928"
RUNTIME = RC / "m0/runtime-snapshots/pilot-runtime-v1"
OUT = RC / "pilot/v7r1-launch"
BASE = ROOT / "configs/council-pilot-local.toml"
SEEDS = (2901, 2902, 2903)
HEADER = (
    "# Council pilot v7r1, seed {seed} (both arms). Runs from pilot-runtime-v1 (native-final-v7 plus\n"
    "# 3 training-only modules, admission-scope decision v1). CPU throughput layout 64/8/4, worker inference.\n"
    "# Generated by pilot/v7r1-launch/make_configs.py from configs/council-pilot-local.toml; do not edit.\n"
    "# Requires the ledger-issued m0-tier-a-fresh-v7 admission receipt (source_root native-final-v7).\n"
)
INSERT_AFTER = "device"


def changes(seed: int) -> dict[str, object]:
    return {
        "source_root": str(RUNTIME),
        "gamedata_path": str(RUNTIME / "gamedata.json"),
        "source_pins_path": str(RUNTIME / "pilot-source-pins.json"),
        "nominal_admission_path": str(RC / "m0/readiness/tier-a-fresh-v7/admission.json"),
        "output_dir": str(OUT / f"runs/s{seed}"),
        "num_envs": 64,
        "actor_workers": 8,
        "torch_threads": 4,
        "smoke_decisions": 98304,
        "rollout_inference": "worker",
        "inference_device": "cpu",
    }


def render(seed: int) -> str:
    text = BASE.read_text()
    lines = text.splitlines(keepends=True)
    assert lines[0].startswith("#"), "base header comment moved"
    body = lines[1:]
    inserted: list[str] = []
    for key, value in changes(seed).items():
        literal = json.dumps(value) if isinstance(value, str) else str(value)
        pattern = re.compile(rf"^{re.escape(key)} = .*$")
        hits = [i for i, line in enumerate(body) if pattern.match(line.rstrip("\n"))]
        assert len(hits) <= 1, (key, hits)
        if hits:
            body[hits[0]] = f"{key} = {literal}\n"
        else:
            inserted.append(f"{key} = {literal}\n")
    anchor = [i for i, line in enumerate(body) if line.startswith(f"{INSERT_AFTER} = ")]
    assert len(anchor) == 1, anchor
    body[anchor[0] + 1 : anchor[0] + 1] = inserted
    return HEADER.format(seed=seed) + "".join(body)


def main() -> None:
    (OUT / "configs").mkdir(parents=True, exist_ok=True)
    for seed in SEEDS:
        path = OUT / "configs" / f"council-pilot-v7r1-seed{seed}.toml"
        with path.open("x") as stream:
            stream.write(render(seed))
        path.chmod(0o444)
        print(path)


if __name__ == "__main__":
    main()
