import json,shutil,time,hashlib
from pathlib import Path
HERE=Path('/mpac/sdicks02/repos/clasher/reports/strategy_council_20260928/search-noise-v2');OPS=HERE/'operations'
stamp=time.strftime('%Y-%m-%d %H:%M:%S UTC',time.gmtime())
note=f'''\n## {stamp} — authorized identical-input recovery r2e\n
The coordinator's adjudication (02:05 UTC entry, confirmed by the explicit recovery task) supersedes the incident stop. The stale Mac transfer is guarded. This was an external technical failure, not a diagnosed frozen-code defect. No reseal, new seeds, engine edit or outcome inspection occurred.

Restoration: all 468 sealed hashes plus manifest verified on 127x01, 127x04 and 127x08. On each of 01 and 04, 41 conflicting files plus the manifest were preserved before replacement from the authenticated frozen-r2 archive. 08 required no replacement. Audits: operations/restoration-audit-<host>-r2e.json. The hub mirror remains active (rsync -au, no deletion); correct source and direct target hash verification establish safety. Original archive and overwritten-* evidence remain intact.

Receipt rule: admit all identity-valid 08 receipts. Admit original 04 receipts only when their own completion time (started + elapsed, the frozen receipt's time fields) is strictly before 2026-10-08T01:39:00Z and the worker terminal log entry precedes all verify failures. Unique original 04: 541 admitted, 94 excluded; excluded recorded game CPU 3.59085004 core-hours. All 94 are preserved in 04's operations/incident-seal-overwrite-r2b/excluded-post-cutoff-127x04-r2e/. The hub held 66 of those excluded replicas (2.34616438 core-hours, already included in the 94, not additive); these too were moved aside. Exact original logs are retained on 01 under operations/original-04-r2/. The collector precheck admitted 1666 unique 08 receipts, zero exclusions; 08 remains active, so this number grows. Backup copies on 04 are counted by receipt origin and deduplicated, not as additional games. Qualification audits contain the complete per-game identity/hash/time decision, without outcomes.

Fresh 04 original attempt: s1-confirm-node-127x04-r2e, indices 0–47, concurrency 45. This conservatively counts Python supervisors/trackers as well as C56's 32 workers against the cap of 80. Original 04 r2 supervisor and 48 exit-1 receipts remain preserved. Frozen workers skip the 541 valid terminal receipts and replay excluded or incomplete games. 08's original r2 supervisor is left unchanged; its grandfathered original launch is not expanded.

Migration: s1-confirm-node-127x04-r2f (48–85; 38 workers) after 04 r2e succeeds; s1-confirm-node-127x08-r2f (86–147; 62 workers) after 08 r2 succeeds. operations/migration_r2e.py is a minimal operational derivative of the reviewed migration_r2b.py: only attempt labels, the 04 successful prerequisite, and monitor filename change. The original split/proof and wrapper stay unchanged. operations/launcher-dry-proof-r2e.json validates the same 38/62 children and original full input digests. All new work uses nice 10 and frozen bootstrap's one-thread native/BLAS settings; launch checks enforce console and host caps.

Collector: s1-collect-r2e on 01, operations/collect_r2e.py. It preserves but disregards 04's superseded r2 failure, requires 04 r2e/r2f and 08 r2/r2f success, rejects any old 04 post-cutoff receipt, tracks all 248 successful done/exit receipts, and admits exactly one immutable receipt per game. It stops on first surviving-host transport/worker failure or identity/action mismatch with no retry. s1-receipt-preserve-r2d was retired only after a successful replacement collection pass, by SIGTERM to its verified Python PID 3369789 (launcher 3369776, time parent 3369788); evidence in preservation-retirement-r2e.json.

Analysis remains outcome-blind until 4992 eligible receipts and 248 successful partitions plus every required supervisor exit exist. At that barrier, one bounded 07 quarantine probe compares identities/action digests against duplicates, never restarts 07, and stops on mismatch. The sealed analysis then runs unchanged through the reviewed host-map facade. Its generated report is preserved before correcting operational engine/exclusion narrative; statistical result.json is untouched. Small docs/audits/results mirror to 05; raw game receipts and runtime binaries stay on fleet.
'''
for name in ('PROGRESS.md','PREREG-r2b-DEVIATION.md'):
    with (HERE/name).open('a') as f:f.write(note)
shutil.copy2(HERE/'RESUME.md',OPS/'RESUME-before-r2e.md')
(HERE/'RESUME.md').write_text('# S1 r2 authorized recovery and complete-only collection\n'+note+'\nLive status: operations/migration-monitor-r2e.json. Inspect exact job PID/exit/locks before any manual resubmission. No retry after a host loss.\n')
proofs={n:hashlib.sha256((OPS/n).read_bytes()).hexdigest() for n in ('migration_r2b.py','migration_r2e.py','migration-split-r2b.json','migration-proof-r2b.json','launcher-dry-proof-r2b.json','launcher-dry-proof-r2e.json','collect_r2e.py')}
(OPS/'recovery-operational-hashes-r2e.json').write_text(json.dumps(dict(utc=time.time(),hashes=proofs),indent=2)+'\n')
