"""Render sealed S1 metadata only, after complete blocks and final host vacancy."""
import argparse,hashlib,html,json,subprocess
from pathlib import Path

ARMS=('K0c-200','S-200','K0c-160','S-160','K2-200')
def ci(point,interval):return f'{point:.2f} [{interval[0]:.2f}, {interval[1]:.2f}]'
def qs(q):return '/'.join(f'{q[k]:.3f}' for k in ('p50','p95','p99','max'))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()

def main():
    ap=argparse.ArgumentParser();ap.add_argument('--data',type=Path,required=True);ap.add_argument('--out',type=Path,required=True);a=ap.parse_args();d=a.data;o=a.out
    results=json.loads((d/'results.json').read_text());gc=json.loads((d/'gc-maintenance.json').read_text());execution=json.loads((d/'execution.json').read_text());vacancy=json.loads((d/'receipts/host-audit-final.json').read_text())
    assert results['checks']['games']==3000 and results['paired_seeds']==600 and not results['smoke_excluded']
    assert vacancy['final'] and not vacancy['own_compute'] and not vacancy['foreign_compute'] and not vacancy['foreign_active']
    assert execution['all_reporting_groups_absent']
    cfg=json.loads((o/'plan.json').read_text());assert results['plan_sha256']==sha(o/'plan.json')
    q=json.loads((d/'receipts/qualification.json').read_text());assert q['states']==125 and all(v==125 for v in q['counts'].values())
    conclusion=results['decision']['conclusion'];utc=subprocess.check_output(['date','-u','+%FT%TZ'],text=True).strip()
    lines=[f'# S1 one-core cached student search', '', f'Completed {utc}. **{conclusion}.**', '', 'Exploration only: 3,000 terminal games, 600 fresh paired seeds per arm; symmetric d=27/capacity1, five decks/25 matchups/alternating seats, the exact K2 plain v1 policy opponent. All five arms run in rotated order on the same physical slot. No Mac, live or heldout access.', '', '| Arm | W/L/D | Loss %, paired-seed 95% CI | Cutoff %, 95% CI | Fallback %, 95% CI | Latency p50/p95/p99/max, ms |', '|---|---:|---:|---:|---:|---:|']
    for arm in ARMS:
        r=results['arms'][arm]
        lines.append(f"| {arm} | {r['wins']}/{r['losses']}/{r['draws']} | {ci(r['loss_pct'],r['loss_ci_pct'])} | {ci(r['cutoff_pct'],r['cutoff_ci_pct'])} | {ci(r['fallback_pct'],r['fallback_ci_pct'])} | {qs(r['wall_ms'])} |")
    lines+=['','| Paired loss contrast | pp, 95% CI |','|---|---:|']
    for label,r in results['contrasts'].items():lines.append(f"| {label} | {ci(r['loss_change_pp'],r['ci95_pp'])} |")
    first=results['contrasts']['S-200 minus K0c-200'];second=results['contrasts']['S-200 minus K2-200']
    lines+=['',f"Frozen rule: S-200−K0c-200 upper CI≤−10 pp and S-200−K2-200 upper CI≤+5 pp. Observed upper bounds {first['ci95_pp'][1]:.2f} pp and {second['ci95_pp'][1]:.2f} pp; component passes {results['decision']['component_passes']}.",'','| Arm | Decisions | Positive overrun count / % | Overrun p50/p95/p99/max, ms | Extra-delay ticks | Cut returns >deadline+8 ms |','|---|---:|---:|---:|---|---:|']
    for arm in ARMS:
        r=results['arms'][arm]
        lines.append(f"| {arm} | {r['decisions']} | {r['overrun_count']} / {r['overrun_pct']:.3f}% | {qs(r['positive_overrun_ms'])} | {json.dumps(r['overrun_ticks_hist'],sort_keys=True)} | {r['cut_past_deadline_plus_reserve_count']} |")
    lines+=['','The timer starts before public observation and charges the single cached model inference, belief preparation, top-8 candidate proposals, public root, scoring and submission. Scoring cutoffs are 192/152 ms with an 8 ms reserve. Every positive overrun is retained and charged as ceil(overrun×20) additional ticks to command due time, own availability and timed waits. Partial and late roots never count. The frozen K2 anchor uses its byte-exact WAIT-first two-worker collector; the one-core arms use coarse-first scoring. K0c differs from K2’s policy-only K0 and the earlier R3 mirror.','', '| Arm | GC count / generation counts | Pause p50/p95/p99/max, ms | >50/250/500 ms counts | GC ms per simulated game minute | During decision |','|---|---:|---:|---:|---:|---:|']
    for arm in ARMS:
        g=gc['arms'][arm]
        # GC supplement retains the inherited schema verbatim.
        count=g['count']
        gens=g['generation_counts']
        distribution=g['pause_ms']
        lines.append(f"| {arm} | {count} / {json.dumps(gens,sort_keys=True)} | {qs(distribution)} | {g['count_above_ms']['50']}/{g['count_above_ms']['250']}/{g['count_above_ms']['500']} | {g['pause_ms_per_game_minute']:.3f} | 0 |")
    lines+=['','GC is deferred only during decisions and remains in whole-game wall/CPU. Maintenance does not advance simulated ticks or incur decision lateness. The inherited instrumentation has no pause timestamps or live poll/opportunity state; maintenance overlap and resulting live loss remain unknown. Zero collections during a decision does not prove zero delayed live polls.','',f"Qualifications: 125/125 frozen coarse-first and K2 no-deadline actions/candidates/scores/root checks; exact proposal-augmented frozen scoring; cached-v1 versus double-inference actions/proposals/RNG; cached student versus canonical R3 TimedPolicy; charged student inference assertions; injected-clock, non-drain/pool-reuse, belief and GC tests. Excluded 40-game smoke passed. [Qualification](receipts/qualification.json), [tests](receipts/qualification.log), [belief qualification](receipts/belief-qualification.json).",'',f"Statistics: {cfg['bootstrap']['reps']} shared paired-seed percentile bootstrap resamples, RNG {cfg['bootstrap']['seed']}; unadjusted pointwise 95% CIs. Draws remain separate. Cutoff/fallback/overrun intervals resample per-game numerator and denominator totals. No early outcome reduction, optional stopping or outcome-dependent retuning.",'',f"Source freeze {execution['freeze_commit']}; native SHA {execution['native_sha256']}; R3a EMA SHA {cfg['student']['checkpoint_sha256']}; threshold {cfg['student']['threshold']}. Reporting {cfg['seed_ranges']['reporting']['base']}+[0,600), excluded smoke {cfg['seed_ranges']['smoke']['base']}+[0,8). [Plan](PLAN.md), [seed audit](seed-audit.json), [raw hashes/statistics](results.json), [runtime pin](receipts/runtime-pin.json), [execution audit](receipts/execution.json), [GC supplement](gc-maintenance.json).",'',f"Fleet: 127x01 only, physical 0–39, nice10/SCHED_OTHER; K2 uses two workers plus main (3 cores), others one core. R3 priority and final release were independently checked before S1. All reporting PGIDs exited and [final vacancy](receipts/host-audit-final.json) passed. Whole-tree study CPU {execution['whole_tree_cpu_hours']:.3f} hours; nested per-game diagnostic CPU is not added again. Small repository authoring, transfer sender, scanner and independent metadata audit overhead is disclosed separately.",'','R3a remains killed and NEVER-ADOPTABLE under its original Stage 1 gates. This study reports a compute-tier comparison and does not override those gates. Fleet strength does not qualify loaded Mac timing or live admission; see [S1 Mac tier](MAC-TIER.md).','']
    (o/'RESULTS.md').write_text('\n'.join(lines))
    note=[ '# S1 Mac tier note','',f'Updated {utc}. Linux-only results: **{conclusion}**.', '',f"S-200−K0c-200: {ci(first['loss_change_pp'],first['ci95_pp'])} pp; S-200−K2-200: {ci(second['loss_change_pp'],second['ci95_pp'])} pp. The frozen viability thresholds are upper CI≤−10 pp and≤+5 pp, respectively.",'',f"S-160−S-200 degradation: {ci(results['contrasts']['S-160 minus S-200']['loss_change_pp'],results['contrasts']['S-160 minus S-200']['ci95_pp'])} pp. Nominal 0.8× speed emulation uses the shorter 160 ms deadline; the scoring-budget ratio is 152/192 = 0.792. This is budget equivalence, not measured Mac throughput.",'','No Mac access, deployment or live strength admission occurred. R3a’s original Stage 1 kill and NEVER-ADOPTABLE status remain unchanged. A passing result supports only the tested fleet compute tier.','', 'Loaded Mac qualification still requires the existing frame-to-submission, FPS, packet gap, command acceptance and integration gates; actual perception/emulator load; the four-belief-root pipeline; a separately pinned arm64 native build; exact score/posterior/RNG equality; charged inference; all positive overruns and cutoff return tails; and timestamped GC maintenance/poll-opportunity overlap. Fleet GC deferral does not establish zero delayed live polls.','', '[Results](RESULTS.md), [existing Mac requirements](../k-v2/MAC-E4-V2.md).','']
    (o/'MAC-TIER.md').write_text('\n'.join(note))
    cards=[]
    for arm in ARMS:
        r=results['arms'][arm];width=r['loss_pct']
        cards.append(f'<tr><th>{html.escape(arm)}</th><td><div class="bar" style="width:{width}%"></div></td><td>{ci(width,r["loss_ci_pct"])}</td><td>{r["fallback_pct"]:.1f}%</td></tr>')
    (o/'results.html').write_text('<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>S1 study</title><style>body{font:16px system-ui;background:#101824;color:#eaf1ff;max-width:980px;margin:40px auto;padding:20px}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:14px;border-bottom:1px solid #334155}td:nth-child(2){width:35%;background:#172638}.bar{height:18px;background:#38bdf8;border-radius:3px}p{line-height:1.6;color:#cbd5e1}</style><h1>S1 one-core student search</h1><p>'+html.escape(conclusion)+'</p><table><thead><tr><th>Arm</th><th>Loss</th><th>Loss %, 95% CI</th><th>Fallback</th></tr></thead><tbody>'+''.join(cards)+'</tbody></table><p>600 fresh paired seeds per arm · plain v1 opponent · d=27 · honest lateness · 127x01 only</p><p>S-200 − cached v1: '+html.escape(ci(first['loss_change_pp'],first['ci95_pp']))+' pp. S-200 − K2 anchor: '+html.escape(ci(second['loss_change_pp'],second['ci95_pp']))+' pp.</p><p>Exploration only. No Mac/live admission. Original R3a Stage 1 kill remains unchanged.</p></html>')
if __name__=='__main__':main()
