"""Self-contained HTML for completed paired sweep; no external assets."""
import json
from pathlib import Path
p=Path(__file__).parent;r=json.loads((p/'results.json').read_text());assert r['paired_seeds']==600
payload=json.dumps({k:v for k,v in r.items() if k!='file_shas'})
html='''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>
body{margin:0;color:var(--foreground,#202329);font:14px var(--font-sans,system-ui)}h2{font-size:20px;margin:0 0 6px}p{color:var(--muted-foreground,#606775);line-height:1.5;margin:6px 0 14px}select{background:var(--card,#fff);color:inherit;border:1px solid var(--border,#ccd);border-radius:6px;padding:7px;font:inherit}svg{display:block;width:100%;height:250px;margin-top:12px}table{border-collapse:collapse;width:100%;font-size:13px}th,td{text-align:right;padding:9px 5px;border-bottom:1px solid var(--border,#ddd)}th:first-child,td:first-child{text-align:left}th{color:var(--muted-foreground,#606775);font-weight:500}.note{font-size:12px}.good{color:var(--success,#218254)}.row{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.axis{fill:var(--muted-foreground,#606775);font:12px system-ui}.grid{stroke:var(--border,#ddd)}@media(max-width:430px){th,td{font-size:11px;padding:8px 3px}h2{font-size:18px}}
</style></head><body><h2>Honest latency: four K-v2 arms</h2><p>600 fresh paired seeds per arm · v1 opponent · normal priority · four scorer threads for W · 5 physical cores per game</p><div class="row"><label for="metric">Show</label><select id="metric"><option value="contrast">Loss change vs K0-200</option><option value="cutoff">Cutoff rate</option><option value="wall">Full decision p99</option></select></div><svg id="chart" viewBox="0 0 700 250" role="img" aria-label="Deadline sweep chart"></svg><table><thead><tr><th>Arm</th><th>Loss</th><th>Paired change, 95% CI</th><th>Cutoff</th><th>Wall p99</th></tr></thead><tbody id="rows"></tbody></table><p id="speed"></p><p class="note">Loss-change intervals use 5,000 shared paired-seed bootstrap resamples. −10 pp is the frozen advance threshold. Every overrun delays the action by ceil(overrun × 20) game ticks. This one-root fleet sweep is a budget emulation; loaded four-root Mac qualification remains required.</p><script>
const D=__DATA__,A=D.arms,$=s=>document.querySelector(s),names=['V120','V160','V200'],x=[125,350,575];
const f=(n,d=2)=>Number(n).toFixed(d),ci=v=>`[${f(v[0])}, ${f(v[1])}]`;
$('#rows').innerHTML=['V200','V160','V120','K0-200'].map(n=>{const a=A[n];return `<tr><td>${n}</td><td>${f(a.loss_pct)}%</td><td>${f(a.loss_change_pp)} pp ${ci(a.loss_change_ci_pp)}</td><td>${f(a.cutoff_pct)}%</td><td>${f(a.wall_ms.p99,1)} ms</td></tr>`}).join('');
const s=D.minimum_speed;$('#speed').textContent=s.minimum_tested_qualified_ratio===null?'No tested speed satisfies the −10 pp confidence gate.':`Minimum tested speed passing the −10 pp confidence gate: ${f(s.minimum_tested_qualified_ratio)}× fleet. ${s.point_interpolated_crossing_ratio===null?'Point crossing is not bracketed.':`Point interpolation: ${f(s.point_interpolated_crossing_ratio,3)}×; not a qualification.`}`;
function draw(){const metric=$('#metric').value,vals=names.map(n=>metric==='contrast'?A[n].loss_change_pp:metric==='cutoff'?A[n].cutoff_pct:A[n].wall_ms.p99),bounds=names.map(n=>metric==='contrast'?A[n].loss_change_ci_pp:metric==='cutoff'?A[n].cutoff_ci_pct:[A[n].wall_ms.p99,A[n].wall_ms.p99]);let lo=Math.min(0,...bounds.flat()),hi=Math.max(0,...bounds.flat());if(metric==='contrast')lo=Math.min(lo,-10);const pad=Math.max(3,(hi-lo)*.15);lo-=pad;hi+=pad;const y=v=>205-(v-lo)/(hi-lo)*170;let out='';for(let i=0;i<5;i++){const v=lo+(hi-lo)*i/4;out+=`<line class="grid" x1="55" x2="670" y1="${y(v)}" y2="${y(v)}"/><text class="axis" text-anchor="end" x="48" y="${y(v)+4}">${f(v,0)}</text>`}if(metric==='contrast')out+=`<line x1="55" x2="670" y1="${y(-10)}" y2="${y(-10)}" stroke="var(--success,#218254)" stroke-dasharray="5 5"/><text class="axis" x="60" y="${y(-10)-6}">−10 pp advance gate</text>`;out+=`<polyline points="${vals.map((v,i)=>x[i]+','+y(v)).join(' ')}" stroke="var(--chart-1,#5075db)" fill="none" stroke-width="2"/>`;vals.forEach((v,i)=>{out+=`<line x1="${x[i]}" x2="${x[i]}" y1="${y(bounds[i][0])}" y2="${y(bounds[i][1])}" stroke="var(--chart-1,#5075db)" stroke-width="2"/><circle cx="${x[i]}" cy="${y(v)}" r="5" fill="var(--chart-1,#5075db)"/><text class="axis" text-anchor="middle" x="${x[i]}" y="235">${names[i]} · ${[120,160,200][i]} ms</text>`});$('#chart').innerHTML=out;console.log('Rendered',metric,'600 paired seeds per arm')}
$('#metric').addEventListener('change',draw);draw();
</script></body></html>'''.replace('__DATA__',payload)
(p/'results.html').write_text(html)
